/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-bright": "#f8f9fa",
        "error": "#ba1a1a",
        "tertiary-container": "#d58c00",
        "background": "#f8f9fa",
        "surface-container": "#edeeef",
        "secondary-fixed-dim": "#96ccff",
        "primary": "#006e1c",
        "secondary": "#00639a",
        "surface-tint": "#006e1c",
        "surface-container-highest": "#e1e3e4",
        "on-primary-container": "#003c0b",
        "primary-fixed-dim": "#78dc77",
        "on-surface": "#191c1d",
        "secondary-fixed": "#cee5ff",
        "on-secondary-fixed-variant": "#004a75",
        "on-primary": "#ffffff",
        "error-container": "#ffdad6",
        "on-primary-fixed-variant": "#005313",
        "surface-container-low": "#f3f4f5",
        "on-secondary-fixed": "#001d32",
        "on-error": "#ffffff",
        "outline": "#6f7a6b",
        "surface": "#f8f9fa",
        "on-error-container": "#93000a",
        "on-surface-variant": "#3f4a3c",
        "on-primary-fixed": "#002204",
        "inverse-surface": "#2e3132",
        "inverse-primary": "#78dc77",
        "outline-variant": "#becab9",
        "surface-container-high": "#e7e8e9",
        "primary-fixed": "#94f990",
        "on-tertiary": "#ffffff",
        "tertiary": "#835400",
        "on-tertiary-fixed": "#2a1800",
        "inverse-on-surface": "#f0f1f2",
        "tertiary-fixed": "#ffddb5",
        "on-secondary": "#ffffff",
        "surface-container-lowest": "#ffffff",
        "on-secondary-container": "#00436a",
        "tertiary-fixed-dim": "#ffb957",
        "on-background": "#191c1d",
        "secondary-container": "#51b2fe",
        "surface-variant": "#e1e3e4",
        "on-tertiary-container": "#492d00",
        "primary-container": "#4caf50",
        "surface-dim": "#d9dadb",
        "on-tertiary-fixed-variant": "#643f00"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "margin-mobile": "16px",
        "section-gap-desktop": "120px",
        "base": "8px",
        "section-gap-mobile": "64px",
        "container-max": "1280px",
        "gutter": "24px"
      },
      fontFamily: {
        "display-lg-mobile": ["Montserrat", "sans-serif"],
        "label-md": ["Inter", "sans-serif"],
        "display-lg": ["Montserrat", "sans-serif"],
        "headline-md": ["Montserrat", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "headline-sm": ["Montserrat", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "label-sm": ["Inter", "sans-serif"]
      },
      fontSize: {
        "display-lg-mobile": ["36px", { lineHeight: "1.2", fontWeight: "700" }],
        "label-md": ["14px", { lineHeight: "1.2", letterSpacing: "0.05em", fontWeight: "600" }],
        "display-lg": ["56px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-md": ["32px", { lineHeight: "1.3", fontWeight: "600" }],
        "body-md": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        "headline-sm": ["24px", { lineHeight: "1.3", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "label-sm": ["12px", { lineHeight: "1.2", fontWeight: "500" }]
      }
    },
  },
  plugins: [],
}
